# Site settings
title: Hasan Tayyar Besik 
email: tayyar.besik@gmail.com
description: "Hasan Tayyar Besik personal web page where you can find information about him."
baseurl: ""
url: "https://hasantayyar.net/"
twitter_username: htayyar
github_username:  hasantayyar

# Build settings
highlighter: true
markdown: redcarpet
permalink: pretty

collections:
  - medium_posts

