# Site settings
title: Hasan Tayyar BESIK 
email: tayyar.besik@gmail.com
description: "software developer, anti-capitalist, bitwala developer, #nodejs, #devops, former onedio developer"
baseurl: ""
url: "https://hasantayyar.net/"
twitter_username: htayyar
github_username:  hasantayyar

# Build settings
highlighter: true
markdown: redcarpet
permalink: pretty
