# Site settings
title: Hasan Tayyar Besik 
email: tayyar.besik@gmail.com
description: "H8s - Google Cloud Engineer, AWS Solution Architect, Devops, Nodejs"
baseurl: ""
url: "https://hasantayyar.net/"
twitter_username: htayyar
github_username:  hasantayyar

# Build settings
highlighter: true
markdown: redcarpet
permalink: pretty

collections:
  - medium_posts

